api_platform:

    title: "Atypick-house"
    # description: "This is the official API of the Teach'r applications. Its usage is reserved to firm developers only."

    # mapping:
    #     paths: ['%kernel.project_dir%/src/Entity']

    # collection:
    #     pagination:
    #         items_per_page: 30
    swagger:
             api_keys:
                 apiKey:
                    name: Authorization
                    type: header
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        jsonapi:  ['application/vnd.api+json']
        html:     ['text/html']
        csv:      ['text/csv']


    # exception_to_status:
    #     # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
    #     Symfony\Component\Serializer\Exception\ExceptionInterface: 400
    #     ApiPlatform\Core\Exception\InvalidArgumentException: 400
    #     ApiPlatform\Core\Exception\FilterValidationException: 400
    #     Doctrine\ORM\OptimisticLockException: 409

    #     # Custom mapping
    #     App\Exception\InvalidFirebaseAuthToken: 400
    #     App\Exception\FirebaseUserAlreadyExists: 400
    #     App\Exception\DatabaseCorruption: 500
    #     App\Exception\TeachrNotValidated: 403